#include "common.h"
//#include "DestructorDemo.h"

void test()
{
    //destructor_demo();
    //destructor_demo_3();
    //destructor_demo_4();
    //fromLocal8Bit_demo();
    //qstringToUnsignedCharArray();
    //qstringToCharArray();
    //debugQtSource();
    //byteArrayToHexStringDemo();
    //QStringToConstCharPointer();
    //runProgramInExplorerProcess();
    //coreDumpTest();
    //hexStringTest();
    //qapplication_exit();
    //base64_encode();
    //chineseToHexInteger();
    //QTreeWidget_demo();
    //QMenu_demo();
    //QList_demo();
    //QMap_demo();
    //QUuid_demo();
    //testHexQStringToByteArray();
    //drawCircleInPixmap();
	//QDateTime_demo();
	//mouseclick_test();
	//QGridLayout_demo();
	//QFormLayout_demo();
	//recursiveMutex();
    //QVariantToFloat();
    //getWorkingDir();
    //workerSlot();
    //getHostMacAddress();
	//playAudioDemo();
	//tts();
    //QStorageInfoDemo();d
    //QTimerDemo();
    //google_breakpad_test();
    //SignalTest();
    //wmic_demo();
    //destructorDemo();
    //read_qint32_from_qbytearray();
    //signalSlotCopyTest();
    //outputCitys();
    //QTableWidgetTest();
    //deleteLaterTest();
    //getIPTest();
    qfileinfo_test();
}